<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ros2_snapd</name>
  <version>0.0.1</version>
  <description>This package allows to start/stop snap services from ROS 2 services.</description>

  <maintainer email="ubuntu-robotics@canonical.com">Ubuntu Robotics</maintainer>

  <license>GPL-3.0</license>

  <author email="jeremie.deray@canonical.com">Jeremie Deray</author>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>
  <build_depend>ros_snapd_interfaces</build_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>ros_snapd_interfaces</exec_depend>

  <test_depend>ament_cmake_pytest</test_depend>
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
