name: ros2-snapd
base: core24
version: git
summary: A ROS 2 node to start and stop snap services.
description: |
  This snap contains a ROS 2 Jazzy node that exposes ROS 2 services
  which allow to interact with snap services.

  Make sure to install the `ros2-snapd` interfaces:
  apt install ros-jazzy-ros-snapd-interfaces

  To list available snap service:
  ros2 service call /ros2_snapd/list ros_snapd_interfaces/srv/SnapdList

  To start, stop and restart snap service:
  ros2 service call /ros2_snapd/start ros_snapd_interfaces/srv/SnapdStart "service: 'service.name'"
  ros2 service call /ros2_snapd/stop ros_snapd_interfaces/srv/SnapdStop "service: 'service.name'"
  ros2 service call /ros2_snapd/restart ros_snapd_interfaces/srv/SnapdRestart "service: 'service.name'"

website: https://github.com/canonical/ros_snapd
source-code: https://github.com/canonical/ros_snapd
issues: https://github.com/canonical/ros_snapd/issues
contact: ubuntu-robotics-community@canonical.com

license: GPL-3.0

grade: stable
confinement: strict
platforms:
  amd64:
  arm64:

apps:
  ros2-snapd:
    command: ros2 run ros2_snapd ros2_snapd
    daemon: simple
    environment:
      ROS_HOME: $SNAP_DATA/ros
      FASTRTPS_DEFAULT_PROFILES_FILE: ${SNAP}/usr/share/fastdds_no_shared_memory.xml
    plugs: [network, network-bind, ros-snapd-support]
    extensions: [ros2-jazzy-ros-base]

parts:
  snapd-http:
    plugin: python
    python-packages: [snap-http]
    # temporarily adding git to list of build-packages
    # to solve https://github.com/canonical/snapcraft/issues/4805.
    build-packages: [git]
    source: .

  ros2-snapd:
    plugin: colcon
    source: .
    build-packages: [python3-lark]

  config:
    plugin: dump
    source: snap/local/
    organize:
      'fastdds_no_shared_memory.xml': usr/share/
