name: ros2-snapd
base: core24
version: '0.0.1'
summary: A ROS 2 node to start and stop snap services.
description: |
  This snap contains a ROS 2 Jazzy node that exposes ROS 2 services
  which allow to interact with snap services.

  To list available snap service:
  ros2 service call /ros2_snapd/list ros2_snapd/srv/SnapdList

  To start, stop and restart snap service:
  ros2 service call /ros2_snapd/start ros2_snapd/srv/SnapdStart "service: 'service.name'"
  ros2 service call /ros2_snapd/stop ros2_snapd/srv/SnapdStop "service: 'service.name'"
  ros2 service call /ros2_snapd/restart ros2_snapd/srv/SnapdRestart "service: 'service.name'"

license: GPL-3.0
contact: ubuntu-robotics-community@canonical.com
website: https://github.com/ubuntu-robotics/ros_snapd

grade: stable
confinement: strict
architectures:
  - build-on: [amd64]
  - build-on: [arm64]

apps:
  ros2-snapd:
    command: ros2 run ros2_snapd ros2_snapd
    daemon: simple
    environment:
      ROS_HOME: $SNAP_DATA/ros
      FASTRTPS_DEFAULT_PROFILES_FILE: ${SNAP}/usr/share/fastdds_no_shared_memory.xml
    plugs: [network, network-bind, snapd-control]
    extensions: [ros2-jazzy-ros-base]

parts:
  snapd-http:
    plugin: python
    python-packages: [snap-http]
    source: .

  ros2-snapd:
    plugin: colcon
    source: .
    build-packages: [python3-lark]

  config:
    plugin: dump
    source: snap/local/
    organize:
      'fastdds_no_shared_memory.xml': usr/share/
