name: Monthly
on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  noetic:
    uses: canonical/ros_snapd/.github/workflows/snap.yaml@noetic
    secrets: inherit
    with:
      git-ref: "noetic"
  humble:
    uses: canonical/ros_snapd/.github/workflows/snap.yaml@humble
    secrets: inherit
    with:
      git-ref: "humble"
  jazzy:
    uses: canonical/ros_snapd/.github/workflows/snap.yaml@jazzy
    secrets: inherit
    with:
      git-ref: "jazzy"
