name: snap
on:
  push:
    branches:
      - lyrical
  pull_request:
    branches:
      - lyrical
  workflow_dispatch:
  workflow_call:
    inputs:
      git-ref:
        required: false
        type: string
        default: ${{ github.ref }}

jobs:
  snap:
    permissions:
      contents: read
      actions: write
    uses: canonical/robotics-actions-workflows/.github/workflows/snap.yaml@main
    secrets:
      snapstore-login: ${{ secrets.STORE_LOGIN }}
    with:
      git-ref: ${{ inputs.git-ref }}
      runs-on: '["ubuntu-latest", "ubuntu-24.04-arm" ]'
      snapcraft-enable-experimental-extensions: true
      snap-track: lyrical
      snap-risk: candidate
      snap-test-script: |
        #!/bin/bash

        check_existence() {
          local topic_or_node="${1}"
          local name="${2}"
          local timeout="${3}"
          local start_time=$(date +%s)
          local error_code=0

          while true; do
            error_code=$(ros2 "${topic_or_node}" list | grep -q "${name}"; echo $?)
            if [ $error_code -eq 0 ]; then
              echo "${name} is running."
              return 0
            fi

            local current_time=$(date +%s)
            local elapsed_time=$((current_time - start_time))

            if [ $elapsed_time -ge $timeout ]; then
              echo "Error $name is not running."
              exit 1
            fi
            sleep 1
          done
        }

        ## Connect interface
        sudo snap connect ros2-snapd:ros-snapd-support
        sudo snap restart ros2-snapd

        ## Install ROS 2 cli
        sudo snap install ros2-cli --channel=lyrical/edge

        ## check that services are available
        check_existence service /ros2_snapd/list 30
        check_existence service /ros2_snapd/start 30
        check_existence service /ros2_snapd/stop 30
        check_existence service /ros2_snapd/restart 30

        ## @todo test all services

        sudo snap stop ros2-snapd
